/*!
[![Build Status](https://github.com/jaemk/migrant/actions/workflows/ci.yml/badge.svg)](https://github.com/jaemk/migrant/actions)
[![crates.io:migrant_lib](https://img.shields.io/crates/v/migrant_lib.svg?label=migrant_lib)](https://crates.io/crates/migrant_lib)
[![docs](https://docs.rs/migrant_lib/badge.svg)](https://docs.rs/migrant_lib)

> Embeddable migration management
>
> Also see [`migrant`](https://github.com/jaemk/migrant) CLI

`migrant_lib` allows defining and embedding management of database migrations and
(connection) configuration in your compiled application.


**Available Features:**

| Feature       |    Backend                   |
|---------------|------------------------------|
| `d-postgres`  | Enable postgres connectivity |
| `d-sqlite`    | Enable sqlite connectivity   |
| `d-mysql`     | Enable mysql connectivity    |
| `d-all`       | Enable all backends          |


*Notes:*

- No features are enabled by default
- The `d-sqlite` feature does not use `rusqlite`s `bundled` feature.
  If you would like `sqlite` to be bundled with your application, you will have to
  include `rusqlite` and enable the `bundled` feature in your project.


## Usage

- Migrations can be defined as files, string literals, or functions.
- File migrations can be either read from files at runtime or embedded in your executable at compile time
  (using [`include_str!`](https://doc.rust-lang.org/std/macro.include_str.html)).
- Migration tags must all be unique and may only contain the characters `[a-z0-9-]`.
  When running in a `cli_compatible` mode (see `Config::use_cli_compatible_tags`), tags must also be
  prefixed with a timestamp, following: `[0-9]{14}_[a-z0-9-]+`.
  See the [embedded_cli_compatible](https://github.com/jaemk/migrant/blob/master/migrant_lib/examples/embedded_cli_compatible.rs)
  example.
- Function migrations must have the signature `fn(ConnConfig) -> Result<(), Box<dyn std::error::Error>>`.
  See the [embedded_programmable](https://github.com/jaemk/migrant/blob/master/migrant_lib/examples/embedded_programmable.rs)
  example for a working sample of function migrations.
- When working with embedded and function migrations, the respective database feature must be
  enabled (`d-postgres` / `d-sqlite` / `d-mysql`).


```rust,no_run
# fn run() -> Result<(), Box<dyn std::error::Error>> {
let mut config = migrant_lib::Config::from_settings_file("path")?;
fn up(_: migrant_lib::ConnConfig) -> Result<(), Box<dyn std::error::Error>> {
    print!(" Up!");
    Ok(())
}

fn down(_: migrant_lib::ConnConfig) -> Result<(), Box<dyn std::error::Error>> {
    print!(" Down!");
    Ok(())
}

# #[cfg(any(feature="d-sqlite", feature="d-postgres", feature="d-mysql"))]
config.use_migrations(&[
    migrant_lib::FileMigration::with_tag("create-users-table")
        .up("migrations/embedded/create_users_table/up.sql")?
        .down("migrations/embedded/create_users_table/down.sql")?
        .boxed(),
    migrant_lib::EmbeddedMigration::with_tag("create-places-table")
        .up(include_str!("../migrations/embedded/create_places_table/up.sql"))
        .down(include_str!("../migrations/embedded/create_places_table/down.sql"))
        .boxed(),
    migrant_lib::FnMigration::with_tag("custom")
        .up(up)
        .down(down)
        .boxed(),
])?;
# Ok(())
# }
# fn main() { run().unwrap(); }
```


## In-memory sqlite databases

With the `d-sqlite` feature, the special database path `:memory:` selects an
in-memory sqlite database. The underlying connection is established once and
kept alive by the `Config` (and shared by all of its clones), so migrations
and application queries all see the same database. Function migrations can
access the live connection through `ConnConfig::sqlite_connection`.

```rust,no_run
# #[cfg(feature = "d-sqlite")]
# fn run() -> Result<(), Box<dyn std::error::Error>> {
let settings = migrant_lib::Settings::configure_sqlite()
    .memory()
    .build()?;
let config = migrant_lib::Config::with_settings(&settings);
config.setup()?;
# Ok(())
# }
```


## CLI Compatibility

Migration management identical to the [`migrant`](https://github.com/jaemk/migrant) CLI tool can also be embedded.
This method only supports file-based migrations (so `FileMigration`s or `EmbeddedMigration`s using `include_str!`)
and those migration files names must be timestamped with the format `[0-9]{14}_[a-z0-9-]+`,
Properly named files can be generated by `migrant_lib::new` or the `migrant` CLI tool.
This is required because migration order is implied by file names which must follow
a specific format and contain a valid timestamp.

See the [migrant_cli_compatible](https://github.com/jaemk/migrant/blob/master/migrant_lib/examples/migrant_cli_compatible.rs)
example for a working sample where migration files and a `Migrant.toml` config file are available at runtime.

See the [embedded_cli_compatible](https://github.com/jaemk/migrant/blob/master/migrant_lib/examples/embedded_cli_compatible.rs)
example for a working sample where the `migrant` CLI tool can be used during development, and database configuration
and migration file contents are embedded in the application.


## Development

See [CONTRIBUTING](https://github.com/jaemk/migrant/blob/master/migrant_lib/CONTRIBUTING.md)

----

*/
#![warn(missing_docs)]

use std::fmt;

mod macros;

pub mod config;
mod connection;
mod drivers;
pub mod errors;
mod migratable;
pub mod migration;
mod migrator;
mod ops;
mod tags;
mod util;

pub use crate::config::{Config, Settings};
pub use crate::connection::ConnConfig;
pub use crate::errors::{Error, Result};
pub use crate::migratable::Migratable;
pub use crate::migration::{EmbeddedMigration, FileMigration, FnMigration};
pub use crate::migrator::{Direction, Migrator};
pub use crate::ops::{
    edit, list, migration_statuses, new, search_for_settings_file, shell, MigrationStatus,
};

/// Re-export of the `rusqlite` crate used by this library, so downstream
/// code interacting with [`Config::sqlite_connection`] can use matching types
#[cfg(feature = "d-sqlite")]
pub use rusqlite;

/// Settings file name: `Migrant.toml`
pub(crate) const CONFIG_FILE: &str = "Migrant.toml";
/// Timestamp format used in migration tags
pub(crate) const DT_FORMAT: &str = "%Y%m%d%H%M%S";
/// Special sqlite database path selecting an in-memory database
pub(crate) const SQLITE_MEMORY_PATH: &str = ":memory:";

/// Database type being used
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub enum DbKind {
    /// Sqlite database
    Sqlite,
    /// Postgres database
    Postgres,
    /// MySQL database
    MySql,
}

impl std::str::FromStr for DbKind {
    type Err = Error;
    fn from_str(s: &str) -> Result<Self> {
        Ok(match s {
            "sqlite" => DbKind::Sqlite,
            "postgres" => DbKind::Postgres,
            "mysql" => DbKind::MySql,
            _ => {
                return Err(Error::InvalidDbKind(format!(
                    "Invalid Database Kind: {}",
                    s
                )))
            }
        })
    }
}

impl fmt::Display for DbKind {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            DbKind::Postgres => write!(f, "postgres"),
            DbKind::Sqlite => write!(f, "sqlite"),
            DbKind::MySql => write!(f, "mysql"),
        }
    }
}
