/*!
Migration tag validation
*/

/// A "simple" tag contains only `[a-z0-9-]` characters
pub(crate) fn is_valid_simple_tag(tag: &str) -> bool {
    !tag.is_empty()
        && tag
            .bytes()
            .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'-')
}

/// A "full" tag is a simple tag prefixed with a 14-digit timestamp: `[0-9]{14}_[a-z0-9-]+`
///
/// This is the format generated by the `migrant` CLI tool and `migrant_lib::new`
pub(crate) fn is_valid_full_tag(tag: &str) -> bool {
    match tag.split_once('_') {
        Some((stamp, rest)) => {
            stamp.len() == 14
                && stamp.bytes().all(|b| b.is_ascii_digit())
                && is_valid_simple_tag(rest)
        }
        None => false,
    }
}

/// A simple tag optionally prefixed with a timestamp: `([0-9]{14}_)?[a-z0-9-]+`
pub(crate) fn is_valid_opt_stamped_tag(tag: &str) -> bool {
    is_valid_simple_tag(tag) || is_valid_full_tag(tag)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn simple_tags() {
        assert!(is_valid_simple_tag("initial"));
        assert!(is_valid_simple_tag("create-users-table"));
        assert!(is_valid_simple_tag("v2"));
        assert!(!is_valid_simple_tag(""));
        assert!(!is_valid_simple_tag("Initial"));
        assert!(!is_valid_simple_tag("with_underscore"));
        assert!(!is_valid_simple_tag("with space"));
    }

    #[test]
    fn full_tags() {
        assert!(is_valid_full_tag("20170812145327_initial"));
        assert!(is_valid_full_tag("20170812145327_create-users"));
        assert!(!is_valid_full_tag("initial"));
        assert!(!is_valid_full_tag("2017_initial"));
        assert!(!is_valid_full_tag("2017081214532x_initial"));
        assert!(!is_valid_full_tag("20170812145327_"));
        assert!(!is_valid_full_tag("20170812145327_two_parts"));
    }

    #[test]
    fn opt_stamped_tags() {
        assert!(is_valid_opt_stamped_tag("initial"));
        assert!(is_valid_opt_stamped_tag("20170812145327_initial"));
        assert!(!is_valid_opt_stamped_tag("bad_tag"));
        assert!(!is_valid_opt_stamped_tag("Initial"));
    }
}
